# Compose schema version
version: '3.3'

# Overriding settings
services:
  reducer:
    volumes:
      - ${HOST_REPO_DIR:-.}:/app
      - ${HOST_REPO_DIR:-.}/config/settings-api-server.yaml:/app/config/settings-api-server.yaml
