network_id: fedn-test-network

control:
  state: idle
  context: client.tar.gz
  helper: keras_sequential

statestore:
  type: MongoDB
  mongo_config:
    username: fedn_admin
    password: password
    host: mongo
    port: 6534

storage:
  storage_type: S3
  storage_config:
    storage_hostname: minio
    storage_port: 9000
    storage_access_key: fedn_admin
    storage_secret_key: password
    storage_bucket: fedn-models
    storage_secure_mode: False 