name: Build combiner

on:
  push:
    branches: '*'


jobs:
 
  build:
    
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      working-directory: .
    steps:
    
    - uses: actions/checkout@v2
  
    - name: Setup variables
      id: wf-vars
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        echo "name of github basebranch is ${BASE_BRANCH}"
        BRANCH=${GITHUB_REF##*/}
        VERSION=${GITHUB_REF##*-}
        IMAGE_NAME="fedn-combiner"
        IMAGE_TAG="$BRANCH"
        echo ::set-output name=IMAGE_NAME::$IMAGE_NAME
        echo ::set-output name=IMAGE_TAG::$IMAGE_TAG
  
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
       
    - name: docker build fedn-combiner
      env:      
        DOCKER_URL: scaleoutsystems
      working-directory: ${{env.working-directory}}
      run: |
        docker build -t $DOCKER_URL/${{ steps.wf-vars.outputs.IMAGE_NAME }}:${{ steps.wf-vars.outputs.IMAGE_TAG }} -f components/combiner/Dockerfile .
    
    - name: docker push fedn-combiner
      env:      
        DOCKER_URL: scaleoutsystems
      working-directory: ${{env.working-directory}}
      run: |
        docker push $DOCKER_URL/${{ steps.wf-vars.outputs.IMAGE_NAME }}:${{ steps.wf-vars.outputs.IMAGE_TAG }}
